<a href="https://colab.research.google.com/github/paulo-marquesmorgado/EConcepts/blob/main/WorldGovIndicators2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Worldwide Governance Indicators
#### A global compilation of data capturing household, business, and citizen perceptions of the quality of governance in more than 200 countries and territories.

https://www.worldbank.org/en/publication/worldwide-governance-indicators

https://www.worldbank.org/en/publication/worldwide-governance-indicators/interactive-data-access

In [ ]:
# Import necessary libraries
import pandas as pd

In [8]:
import pandas as pd
import requests
from io import BytesIO

# URL of the file on GitHub
url = "https://github.com/paulo-marquesmorgado/EConcepts/raw/main/wgidataset.xlsx"

# Download the file content
response = requests.get(url)

# Read the content into a pandas DataFrame
with pd.ExcelFile(BytesIO(response.content)) as xls:
    # Load the "Data" sheet into df_wgi
    df_wgi = pd.read_excel(xls, sheet_name="Data")
    # Load the "Country" sheet into df_countries
    df_countries = pd.read_excel(xls, sheet_name="Country")

# Display the DataFrames
print("Dataframe from GitHub - Data:")
# print(df_wgi.head())
print("\nDataframe from GitHub - Country:")
# print(df_countries.head())

Dataframe from GitHub - Data:

Dataframe from GitHub - Country:

In [9]:
df_wgi

,Country/Territory,Code,Dimention,1996_Estimate,1996_StdErr,1996_NumSrc,1996_Rank,1996_Lower,1996_Upper,1998_Estimate,...,2021_NumSrc,2021_Rank,2021_Lower,2021_Upper,2022_Estimate,2022_StdErr,2022_NumSrc,2022_Rank,2022_Lower,2022_Upper
0,Aruba,ABW,Voice and Accountability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,80.193237,64.734299,95.652176,1.009182,0.225406,1.0,79.227051,66.666664,93.719810
1,Andorra,AND,Voice and Accountability,1.563217,0.291691,3.0,98.500000,81.500000,100.000000,1.528759,...,2.0,81.159424,66.183578,95.652176,1.102833,0.254695,2.0,85.507248,67.632851,96.135269
2,Afghanistan,AFG,Voice and Accountability,-1.908540,0.261457,4.0,1.000000,0.000000,9.500000,-2.039301,...,9.0,7.246377,1.449275,12.560387,-1.751587,0.132212,9.0,2.415459,0.000000,6.280193
3,Angola,AGO,Voice and Accountability,-1.578164,0.208810,6.0,6.000000,0.500000,13.000000,-1.411879,...,13.0,24.154589,20.289856,29.951691,-0.797131,0.117145,13.0,26.570047,21.739130,31.884058
4,Anguilla,AIA,Voice and Accountability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1279,Serbia,SRB,Control of Corruption,-1.140072,0.262077,4.0,11.827957,0.537634,29.032259,-1.195605,...,9.0,35.714287,26.190475,48.095238,-0.456188,0.158030,9.0,35.377357,24.528301,48.113209
1280,South Africa,ZAF,Control of Corruption,0.732927,0.210325,6.0,76.344086,66.129036,81.182793,0.638809,...,11.0,53.809525,46.190475,60.000000,-0.319765,0.157883,11.0,44.811321,31.603773,52.358490
1281,"Congo, Dem. Rep.",COD,Control of Corruption,-1.647852,0.315914,3.0,0.000000,0.000000,12.365591,-1.416679,...,11.0,4.285714,0.000000,6.666667,-1.544474,0.149016,12.0,3.301887,0.471698,7.075472
1282,Zambia,ZMB,Control of Corruption,-0.840641,0.262077,4.0,24.731182,5.913979,41.397850,-0.853156,...,12.0,25.714285,17.619047,33.809525,-0.529200,0.152557,12.0,34.433964,23.584906,45.754719
1283,Zimbabwe,ZWE,Control of Corruption,-0.278847,0.244907,5.0,47.849461,30.645161,60.752689,-0.504802,...,12.0,10.000000,4.285714,17.619047,-1.255139,0.151262,12.0,8.490566,4.245283,17.924528

In [10]:
df_countries

,COUNTRY,COUNTRY CODE,CODE,ISO CODES,POPULATION,AREA KM2,GDP $USD,Soyrce,Continent,Cultural Regions,Geo Regions,M49 Code,Region 1,Region 2
0,Aruba,297,ABW,AW / ABW,71566.0,193.0,2.516 Billion,https://countrycode.org/,North America,North America,Caribbean,533.0,Caribbean,Latin America and the Caribbean
1,Afghanistan,93,AFG,AF / AFG,29121286.0,647500.0,20.65 Billion,https://countrycode.org/,Asia,Asia,Middle East,4.0,Southern Asia,NaN
2,Angola,244,AGO,AO / AGO,13068161.0,1246700.0,124 Billion,https://countrycode.org/,Africa,Africa,Southern African,24.0,Middle Africa,Sub-Saharan Africa
3,Anguilla,1-264,AIA,AI / AIA,13254.0,102.0,175.4 Million,https://countrycode.org/,North America,North America,Caribbean,660.0,Caribbean,Latin America and the Caribbean
4,Åland Islands,NaN,ALA,NaN,NaN,NaN,NaN,NaN,Europe,Europe,Nordic,248.0,Northern Europe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,Yemen,967,YEM,YE / YEM,23495361.0,527970.0,43.89 Billion,https://countrycode.org/,Asia,Asia,Arabian,887.0,Western Asia,NaN
249,South Africa,27,ZAF,ZA / ZAF,49000000.0,1219912.0,353.9 Billion,https://countrycode.org/,Africa,Africa,Southern African,710.0,Southern Africa,Sub-Saharan Africa
250,Zambia,260,ZMB,ZM / ZMB,13460305.0,752614.0,22.24 Billion,https://countrycode.org/,Africa,Africa,East African,894.0,Eastern Africa,Sub-Saharan Africa
251,Zimbabwe,263,ZWE,ZW / ZWE,11651858.0,390580.0,10.48 Billion,https://countrycode.org/,Africa,Africa,Southern African,716.0,Eastern Africa,Sub-Saharan Africa
252,West Bank and Gaza,NaN,WBG,NaN,NaN,NaN,NaN,NaN,Asia,Asia,Islamic,NaN,Western Asia,NaN

In [11]:
# Assuming df_wgi is your existing DataFrame containing all columns
# Selecting only the desired columns
df_mywgi = df_wgi[['Country/Territory', 'Code', 'Dimention', '2022_Rank']].copy()

# Display the first few rows of df_mywgi
print(df_mywgi.head())

# Merge df_mywgi with df_countries on the 'Code' column
df_merged = df_mywgi.merge(df_countries[['CODE', 'Continent', 'Region 1']],
                           how='left', left_on='Code', right_on='CODE')

# Drop the redundant 'CODE' column
df_merged.drop(columns=['CODE'], inplace=True)

# Display the information about the merged DataFrame
print(df_merged)

  Country/Territory Code                 Dimention  2022_Rank
0             Aruba  ABW  Voice and Accountability  79.227051
1           Andorra  AND  Voice and Accountability  85.507248
2       Afghanistan  AFG  Voice and Accountability   2.415459
3            Angola  AGO  Voice and Accountability  26.570047
4          Anguilla  AIA  Voice and Accountability        NaN
     Country/Territory Code                 Dimention  2022_Rank  \
0                Aruba  ABW  Voice and Accountability  79.227051
1              Andorra  AND  Voice and Accountability  85.507248
2          Afghanistan  AFG  Voice and Accountability   2.415459
3               Angola  AGO  Voice and Accountability  26.570047
4             Anguilla  AIA  Voice and Accountability        NaN
...                ...  ...                       ...        ...
1279            Serbia  SRB     Control of Corruption  35.377357
1280      South Africa  ZAF     Control of Corruption  44.811321
1281  Congo, Dem. Rep.  COD     Control of Corruption   3.301887
1282            Zambia  ZMB     Control of Corruption  34.433964
1283          Zimbabwe  ZWE     Control of Corruption   8.490566

          Continent         Region 1
0     North America        Caribbean
1            Europe  Southern Europe
2              Asia    Southern Asia
3            Africa    Middle Africa
4     North America        Caribbean
...             ...              ...
1279         Europe  Southern Europe
1280         Africa  Southern Africa
1281         Africa    Middle Africa
1282         Africa   Eastern Africa
1283         Africa   Eastern Africa

[1284 rows x 6 columns]

In [12]:
# Get unique values of the 'Dimention' column
unique_dimensions = df_merged['Dimention'].unique()

# Display the unique values
print(unique_dimensions)

['Voice and Accountability'
 'Political Stability and Absence of Violence/Terrorism'
 'Government Effectiveness' 'Regulatory Quality' 'Rule of Law'
 'Control of Corruption']

In [13]:
import pandas as pd

# Define the weights for each dimension
dimension_weights = {
    'Voice and Accountability': 1/6,
    'Political Stability and Absence of Violence/Terrorism': 1/6,
    'Government Effectiveness': 1/6,
    'Regulatory Quality': 1/6,
    'Rule of Law': 1/6,
    'Control of Corruption': 1/6
}

# Initialize an empty DataFrame to store the results
all_results = pd.DataFrame(columns=['Country/Territory', 'Region 1', 'Normalized Weighted Sum'])

# Loop through each unique combination of Continent and Region 1
for continent in df_merged['Continent'].unique():
    for region1 in df_merged[df_merged['Continent'] == continent]['Region 1'].unique():
        # Filter df_merged for the current combination of Continent and Region 1
        df_filtered = df_merged[(df_merged['Continent'] == continent) & (df_merged['Region 1'] == region1)]

        # Pivot the DataFrame to have Country/Territory per row and Dimension per column
        pivot_df = df_filtered.pivot(index='Country/Territory', columns='Dimention', values='2022_Rank')

        # Initialize a DataFrame to store the weighted sum
        weighted_sum = pd.DataFrame(index=pivot_df.index, columns=['Weighted Sum'])

        # Calculate the weighted sum for each country
        for dim, weight in dimension_weights.items():
            dim_weighted = pivot_df[dim] * weight
            weighted_sum['Weighted Sum'] = weighted_sum['Weighted Sum'].add(dim_weighted, fill_value=0)

        # Normalize the weighted sum by dividing by the sum of the weights
        sum_weights = sum(dimension_weights.values())
        weighted_sum_normalized = weighted_sum['Weighted Sum'] / sum_weights

        # Round the normalized weighted sum to 2 decimals using apply and lambda function
        weighted_sum_normalized = weighted_sum_normalized.apply(lambda x: round(x, 2))

        # Create a DataFrame to store the results for the current combination of Region 1
        result_df = pd.DataFrame({'Normalized Weighted Sum': weighted_sum_normalized})

        # Reset index to include 'Country/Territory' as a column
        result_df.reset_index(inplace=True)

        # Add 'Region 1' column with the current value
        result_df['Region 1'] = region1

        # Add 'Continent' column with the current value
        result_df['Continent'] = continent

        # Concatenate the results to the overall DataFrame
        all_results = pd.concat([all_results, result_df], ignore_index=True)

# Sort the DataFrame by Region 1 in ascending order and then by Normalized Weighted Sum in descending order
sorted_result_df = all_results.sort_values(by=['Region 1', 'Normalized Weighted Sum'], ascending=[True, False])

# Display the sorted DataFrame with the 'Normalized Weighted Sum'
# print(sorted_result_df[['Country/Territory', 'Region 1', 'Normalized Weighted Sum']])

# Group the DataFrame by 'Region 1'
grouped_df = sorted_result_df.groupby('Region 1')

# Iterate over each group and print the records followed by an empty line
for name, group in grouped_df:
    print(group.to_string(index=False))
    print()  # Print an empty line after each group

Country/Territory                  Region 1  Normalized Weighted Sum Continent
      New Zealand Australia and New Zealand                    96.62   Oceania
        Australia Australia and New Zealand                    92.27   Oceania

             Country/Territory  Region 1  Normalized Weighted Sum     Continent
                         Aruba Caribbean                    83.64 North America
                Cayman Islands Caribbean                    80.47 North America
                      Barbados Caribbean                    76.83 North America
St. Vincent and the Grenadines Caribbean                    72.14 North America
                      Dominica Caribbean                    70.64 North America
           St. Kitts and Nevis Caribbean                    70.33 North America
                      Anguilla Caribbean                    68.00 North America
                       Grenada Caribbean                    67.96 North America
                     St. Lucia Caribbean                    67.89 North America
                  Bahamas, The Caribbean                    67.67 North America
           Antigua and Barbuda Caribbean                    64.19 North America
                    Martinique Caribbean                    62.42 North America
         Virgin Islands (U.S.) Caribbean                    61.08 North America
                   Puerto Rico Caribbean                    59.99 North America
                       Jamaica Caribbean                    59.77 North America
           Trinidad and Tobago Caribbean                    52.23 North America
            Dominican Republic Caribbean                    50.86 North America
                          Cuba Caribbean                    34.40 North America
                         Haiti Caribbean                     8.16 North America
 Netherlands Antilles (former) Caribbean                      NaN North America

Country/Territory        Region 1  Normalized Weighted Sum     Continent
       Costa Rica Central America                    70.68 North America
           Panama Central America                    48.12 North America
           Belize Central America                    44.35 North America
      El Salvador Central America                    33.87 North America
           Mexico Central America                    31.85 North America
        Guatemala Central America                    25.21 North America
         Honduras Central America                    24.66 North America
        Nicaragua Central America                    15.61 North America

Country/Territory     Region 1  Normalized Weighted Sum Continent
       Kazakhstan Central Asia                    41.35      Asia
       Uzbekistan Central Asia                    28.04      Asia
  Kyrgyz Republic Central Asia                    20.71      Asia
       Tajikistan Central Asia                    12.83      Asia
     Turkmenistan Central Asia                    11.48      Asia

Country/Territory       Region 1  Normalized Weighted Sum Continent
        Mauritius Eastern Africa                    74.16    Africa
       Seychelles Eastern Africa                    72.11    Africa
          Réunion Eastern Africa                    59.83    Africa
           Rwanda Eastern Africa                    52.68    Africa
           Zambia Eastern Africa                    36.73    Africa
         Tanzania Eastern Africa                    35.50    Africa
           Malawi Eastern Africa                    34.95    Africa
            Kenya Eastern Africa                    33.17    Africa
           Uganda Eastern Africa                    27.23    Africa
       Madagascar Eastern Africa                    22.63    Africa
         Ethiopia Eastern Africa                    21.62    Africa
       Mozambique Eastern Africa                    21.51    Africa
         Djibouti Eastern Africa                    20.02    Africa
          Comoros Eastern Africa                    16.45    Africa
         Zimbabwe Eastern Africa                    12.10    Africa
          Burundi Eastern Africa                    10.89    Africa
          Eritrea Eastern Africa                     5.19    Africa
          Somalia Eastern Africa                     1.51    Africa
      South Sudan Eastern Africa                     1.51    Africa

   Country/Territory     Region 1  Normalized Weighted Sum Continent
               Japan Eastern Asia                    89.62      Asia
       Taiwan, China Eastern Asia                    84.37      Asia
         Korea, Rep. Eastern Asia                    79.23      Asia
Hong Kong SAR, China Eastern Asia                    78.60      Asia
    Macao SAR, China Eastern Asia                    76.62      Asia
            Mongolia Eastern Asia                    45.90      Asia
               China Eastern Asia                    41.30      Asia
    Korea, Dem. Rep. Eastern Asia                     7.39      Asia

 Country/Territory       Region 1  Normalized Weighted Sum Continent
    Czech Republic Eastern Europe                    80.58    Europe
   Slovak Republic Eastern Europe                    67.75    Europe
            Poland Eastern Europe                    65.98    Europe
           Hungary Eastern Europe                    62.66    Europe
           Romania Eastern Europe                    59.92    Europe
          Bulgaria Eastern Europe                    52.27    Europe
           Moldova Eastern Europe                    42.34    Europe
           Ukraine Eastern Europe                    28.88    Europe
Russian Federation Eastern Europe                    16.88    Europe
           Belarus Eastern Europe                    15.74    Europe

Country/Territory  Region 1  Normalized Weighted Sum Continent
             Fiji Melanesia                    59.99   Oceania
          Vanuatu Melanesia                    57.50   Oceania
  Solomon Islands Melanesia                    42.84   Oceania
 Papua New Guinea Melanesia                    28.56   Oceania

    Country/Territory   Region 1  Normalized Weighted Sum Continent
                 Guam Micronesia                    79.97   Oceania
                Palau Micronesia                    76.26   Oceania
Micronesia, Fed. Sts. Micronesia                    69.45   Oceania
     Marshall Islands Micronesia                    68.02   Oceania
             Kiribati Micronesia                    67.78   Oceania
                Nauru Micronesia                    64.02   Oceania

       Country/Territory      Region 1  Normalized Weighted Sum Continent
   São Tomé and Principe Middle Africa                    42.36    Africa
                   Gabon Middle Africa                    26.98    Africa
                  Angola Middle Africa                    23.14    Africa
             Congo, Rep. Middle Africa                    17.12    Africa
                Cameroon Middle Africa                    15.87    Africa
       Equatorial Guinea Middle Africa                    12.12    Africa
                    Chad Middle Africa                     8.52    Africa
Central African Republic Middle Africa                     7.14    Africa
        Congo, Dem. Rep. Middle Africa                     6.59    Africa

Country/Territory        Region 1  Normalized Weighted Sum Continent
          Morocco Northern Africa                    41.64    Africa
          Tunisia Northern Africa                    40.33    Africa
 Egypt, Arab Rep. Northern Africa                    25.11    Africa
          Algeria Northern Africa                    23.12    Africa
            Sudan Northern Africa                     6.48    Africa
            Libya Northern Africa                     4.13    Africa

Country/Territory         Region 1  Normalized Weighted Sum     Continent
           Canada Northern America                    90.94 North America
        Greenland Northern America                    88.09 North America
    United States Northern America                    77.88 North America
          Bermuda Northern America                    68.63 North America

      Country/Territory        Region 1  Normalized Weighted Sum Continent
                Denmark Northern Europe                    95.35    Europe
                Finland Northern Europe                    95.28    Europe
                 Norway Northern Europe                    93.79    Europe
                 Sweden Northern Europe                    93.23    Europe
                Iceland Northern Europe                    93.22    Europe
                Ireland Northern Europe                    91.49    Europe
Jersey, Channel Islands Northern Europe                    88.57    Europe
                Estonia Northern Europe                    87.14    Europe
         United Kingdom Northern Europe                    85.49    Europe
              Lithuania Northern Europe                    79.56    Europe
                 Latvia Northern Europe                    75.22    Europe

Country/Territory  Region 1  Normalized Weighted Sum Continent
   American Samoa Polynesia                    81.44   Oceania
            Samoa Polynesia                    70.20   Oceania
           Tuvalu Polynesia                    70.08   Oceania
             Niue Polynesia                    68.92   Oceania
     Cook Islands Polynesia                    60.49   Oceania
            Tonga Polynesia                    59.01   Oceania

Country/Territory      Region 1  Normalized Weighted Sum     Continent
          Uruguay South America                    83.22 South America
    French Guiana South America                    80.23 South America
            Chile South America                    72.24 South America
         Colombia South America                    44.63 South America
           Guyana South America                    44.08 South America
        Argentina South America                    41.44 South America
         Suriname South America                    40.09 South America
           Brazil South America                    39.92 South America
             Peru South America                    37.93 South America
          Ecuador South America                    36.59 South America
         Paraguay South America                    36.04 South America
          Bolivia South America                    24.68 South America
    Venezuela, RB South America                     4.82 South America

Country/Territory           Region 1  Normalized Weighted Sum Continent
        Singapore South-eastern Asia                    89.88      Asia
Brunei Darussalam South-eastern Asia                    76.36      Asia
         Malaysia South-eastern Asia                    63.63      Asia
        Indonesia South-eastern Asia                    48.40      Asia
         Thailand South-eastern Asia                    45.01      Asia
          Vietnam South-eastern Asia                    41.41      Asia
      Philippines South-eastern Asia                    40.19      Asia
      Timor-Leste South-eastern Asia                    39.79      Asia
          Lao PDR South-eastern Asia                    28.09      Asia
         Cambodia South-eastern Asia                    25.13      Asia
          Myanmar South-eastern Asia                     6.45      Asia

Country/Territory        Region 1  Normalized Weighted Sum Continent
         Botswana Southern Africa                    71.39    Africa
          Namibia Southern Africa                    59.76    Africa
     South Africa Southern Africa                    46.65    Africa
          Lesotho Southern Africa                    35.81    Africa
         Eswatini Southern Africa                    26.55    Africa

 Country/Territory      Region 1  Normalized Weighted Sum Continent
            Bhutan Southern Asia                    66.72      Asia
             India Southern Asia                    47.91      Asia
          Maldives Southern Asia                    45.83      Asia
         Sri Lanka Southern Asia                    35.77      Asia
             Nepal Southern Asia                    33.04      Asia
          Pakistan Southern Asia                    21.48      Asia
        Bangladesh Southern Asia                    21.26      Asia
Iran, Islamic Rep. Southern Asia                    11.91      Asia
       Afghanistan Southern Asia                     5.20      Asia

     Country/Territory        Region 1  Normalized Weighted Sum Continent
               Andorra Southern Europe                    90.98    Europe
            San Marino Southern Europe                    89.42    Europe
              Portugal Southern Europe                    80.15    Europe
              Slovenia Southern Europe                    77.27    Europe
                 Malta Southern Europe                    75.41    Europe
                 Spain Southern Europe                    73.19    Europe
                 Italy Southern Europe                    67.38    Europe
               Croatia Southern Europe                    65.51    Europe
                Greece Southern Europe                    62.72    Europe
            Montenegro Southern Europe                    53.52    Europe
       North Macedonia Southern Europe                    52.49    Europe
               Albania Southern Europe                    50.44    Europe
                Serbia Southern Europe                    46.71    Europe
                Kosovo Southern Europe                    41.68    Europe
Bosnia and Herzegovina Southern Europe                    32.22    Europe

Country/Territory       Region 1  Normalized Weighted Sum Continent
       Cape Verde Western Africa                    68.70    Africa
            Ghana Western Africa                    50.47    Africa
          Senegal Western Africa                    47.54    Africa
            Benin Western Africa                    39.14    Africa
      Gambia, The Western Africa                    38.15    Africa
    Côte d'Ivoire Western Africa                    37.17    Africa
     Burkina Faso Western Africa                    29.05    Africa
     Sierra Leone Western Africa                    27.84    Africa
             Togo Western Africa                    27.55    Africa
            Niger Western Africa                    27.27    Africa
          Liberia Western Africa                    24.40    Africa
       Mauritania Western Africa                    24.09    Africa
             Mali Western Africa                    17.31    Africa
          Nigeria Western Africa                    16.79    Africa
           Guinea Western Africa                    16.66    Africa
    Guinea-Bissau Western Africa                    16.65    Africa

   Country/Territory     Region 1  Normalized Weighted Sum Continent
               Qatar Western Asia                    70.44      Asia
United Arab Emirates Western Asia                    70.28      Asia
              Cyprus Western Asia                    69.79    Europe
              Israel Western Asia                    68.50      Asia
             Georgia Western Asia                    60.02    Europe
                Oman Western Asia                    54.08      Asia
              Kuwait Western Asia                    53.02      Asia
             Bahrain Western Asia                    52.63      Asia
        Saudi Arabia Western Asia                    49.56      Asia
              Jordan Western Asia                    49.08      Asia
             Armenia Western Asia                    43.75    Europe
             Türkiye Western Asia                    32.64      Asia
          Azerbaijan Western Asia                    27.87    Europe
  West Bank and Gaza Western Asia                    25.48      Asia
             Lebanon Western Asia                    14.82      Asia
                Iraq Western Asia                     9.99      Asia
         Yemen, Rep. Western Asia                     2.38      Asia
Syrian Arab Republic Western Asia                     1.58      Asia

Country/Territory       Region 1  Normalized Weighted Sum Continent
      Switzerland Western Europe                    96.69    Europe
       Luxembourg Western Europe                    95.66    Europe
    Liechtenstein Western Europe                    95.18    Europe
      Netherlands Western Europe                    91.81    Europe
           Monaco Western Europe                    88.64    Europe
          Germany Western Europe                    88.42    Europe
          Austria Western Europe                    87.08    Europe
          Belgium Western Europe                    84.64    Europe
           France Western Europe                    80.21    Europe